[package]
name = "yes"
edition = "2018"
version = "0.0.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]

[target.'cfg(unix)'.dependencies]
libc = "0.2.48"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.6", features = [ "winbase", "processenv" ] }
